# apps/backend/envs/dev/deployment-patch.yaml
apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: backend-config  
  namespace: devbcn-demo
  annotations:  
    argocd.argoproj.io/sync-wave: "0"    
data:  
  CORS_ALLOWED_ORIGIN: "http://localhost:8080"  