# apps/backend/envs/dev/deployment-patch.yaml
apiVersion: apps/v1  
kind: Deployment 
metadata:  
  name: backend  
  namespace: devbcn-demo
  annotations:  
    argocd.argoproj.io/sync-wave: "2"   
spec:  
  replicas: 2 