# argo-cd/envs/dev/kustomization.yaml  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:  
  - ../../base  
  - restrict-default-project.yaml
  - project-devbcn-demo.yaml
  - project-common-resources.yaml
  
namespace: argocd  
  
patches:  
  - path: argocd-cm-patch.yaml  
  - path: argocd-rbac-cm-patch.yaml  